### ISSUE TITLE
Some jobs assign platforms which are too short for the consist

### ISSUE THREAD

**Issue by zenorbi** [katycat5e/DVPassengerJobs#45]
I got handed a job where the train doesn't fit into the assigned platform even if I reverse in the cars and hit the end-of-track buffer.

Mod version: 4.0.3

![20231126000409_1](https://github.com/katycat5e/DVPassengerJobs/assets/313625/b4df9b73-9dd4-44b8-a9ba-fbdefe84b89b)
![20231126000430_1](https://github.com/katycat5e/DVPassengerJobs/assets/313625/a20036af-d100-48d9-a345-d7aa439c66f8)

**Comment by katycat5e** [comment]
Fixed in #46 (next release)
