### ISSUE TITLE
Light support for custom coaches (CCL)

### ISSUE THREAD

**Issue by WhistleWiz** [katycat5e/DVPassengerJobs#47]
Add the ability to include lights in CCL coaches that work in the same way as the ones added to the vanilla coaches.
This mod would then look for a gameobject with the correct name in the root of the prefab and enable/disable it automatically.

An example:
![image](https://github.com/katycat5e/DVPassengerJobs/assets/9304724/fd1fcdf3-4198-4022-9f6d-3e6fa01e03e3)

**Comment by katycat5e** [comment]
Migrated to CCL repo
